config/routes.rb
Rails.application.routes.draw do
  resources :mascotas
  devise_for :usuarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "mascotas#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mascota.rb
class Mascota < ApplicationRecord
  belongs_to :usuario
  validates :cualidad, presence: true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :mascotas
  enum :rol, [:regular, :admin]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #include Pagy::Backend
    def after_sign_in_path_for(resource)
        mascotas_path
    end

    def after_sign_out_path_for(resource_or_scope)
        mascotas_path # Ruta a la que se redirigirá después de cerrar sesión
    end


       
end

app/controllers/mascotas_controller.rb
class MascotasController < ApplicationController
  before_action :set_mascota, only: %i[ show edit update destroy ]
  before_action :authenticate_usuario!, except: [:index, :show]

  # GET /mascotas or /mascotas.json
  def index
    @mascotas = Mascota.all
    #@pagy, @mascotas = pagy(Mascota.all)
  end

  # GET /mascotas/1 or /mascotas/1.json
  def show
    @mascota = Mascota.includes(:usuario).find(params[:id])
  end

  # GET /mascotas/new
  def new
    @mascota = Mascota.new
    @tipos_mascota = ["Perro", "Gato", "Ave"]
    @ciudades = cargar_ciudades_desde_csv
  end

  # GET /mascotas/1/edit
  def edit
    unless current_usuario.admin? || current_usuario == @mascota.usuario
      redirect_to mascota_path(@mascota), alert: "No tienes permiso para editar esta mascota."
    end
  end

  # POST /mascotas or /mascotas.json
  def create
    @mascota = Mascota.new(mascota_params)
    @mascota.usuario = current_usuario

    respond_to do |format|
      if @mascota.save
        format.html { redirect_to mascota_url(@mascota), notice: "Mascota was successfully created." }
        format.json { render :show, status: :created, location: @mascota }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mascota.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mascotas/1 or /mascotas/1.json
  def update
    unless current_usuario.admin? || current_usuario == @mascota.usuario
      redirect_to mascota_path(@mascota), alert: "No tienes permiso para editar esta mascota."
      return
    end

    respond_to do |format|
      if @mascota.update(mascota_params)
        format.html { redirect_to mascota_url(@mascota), notice: "Mascota was successfully updated." }
        format.json { render :show, status: :ok, location: @mascota }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mascota.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mascotas/1 or /mascotas/1.json
  def destroy
    unless current_usuario.admin? || current_usuario == @mascota.usuario
      redirect_to mascota_path(@mascota), alert: "No tienes permiso para eliminar esta mascota."
      return
    end

    @mascota.destroy

    respond_to do |format|
      format.html { redirect_to mascotas_url, notice: "Mascota was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def cargar_ciudades_desde_csv
      ciudades = []
      require 'csv' 
      CSV.foreach(Rails.root.join('db', 'ciudades.csv')) do |row|
        ciudades << row.first
      end
      ciudades
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_mascota
      @mascota = Mascota.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mascota_params
      params.require(:mascota).permit(:nombre, :apodo, :tipo, :descripcion, :ciudad, :fecha, cualidad: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    #include Pagy::Frontend
end

app/helpers/mascotas_helper.rb
module MascotasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeEncontre</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar'%>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/mascotas/_form.html.erb
<%= form_with(model: mascota) do |form| %>
  <% if mascota.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mascota.errors.count, "error") %> prohibited this mascota from being saved:</h2>

      <ul>
        <% mascota.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
  <%= form.label :apodo, style: "display: block" %>
  <%= form.radio_button :apodo, true %> Sí
  <%= form.radio_button :apodo, false %> No
</div>


  <div>
    <%= form.label :tipo, style: "display: block" %>
    <%= form.select :tipo, @tipos_mascota %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_field :descripcion %>
  </div>

  <div>
    <%= form.label :ciudad, style: "display: block" %>
    <%= form.select :ciudad, @ciudades %>
  </div>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha %>
  </div>

  <div>
  <%= form.label :cualidad, style: "display: block" %>
  <% ['Le gusta correr en el parque.', 'Disfruta nadar en el lago.', 'Prefiere dormir durante el día.',
     'Siempre está listo para comer.', 'Le encanta volar (aplicable para aves).', 'Es amigable con otros animales.',
     'Le gusta jugar con juguetes.', 'Disfruta de los paseos largos.', 'Le encanta ser acariciado.',
     'Es curioso y le gusta explorar.'].each do |option| %>
    <%= form.check_box :cualidad, { multiple: true }, option %>
    <%= option %><br>
  <% end %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mascotas/_mascota.html.erb
<div id="<%= dom_id mascota %>">
  <p>
    <strong>Nombre:</strong>
    <%= mascota.nombre %>
  </p>

  <p>
    <strong>Apodo:</strong>
    <% if mascota.apodo %>
      Sí
    <% else %>
      No
    <% end %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= mascota.tipo %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= mascota.descripcion %>
  </p>

  <p>
    <strong>Ciudad:</strong>
    <%= mascota.ciudad %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= mascota.fecha %>
  </p>

  <p>
    <strong>Cualidad:</strong>
    <%= mascota.cualidad %>
  </p>

  <!-- app/views/mascotas/show.html.erb -->
  <p>
    <strong>Nombre del creador:</strong>
    <%= mascota.usuario.nombre %>
  </p>

  <p>
    <strong>Email del creador:</strong>
    <%= mascota.usuario.email %>
  </p>

  <p>
    <strong>Teléfono del creador:</strong>
    <%= mascota.usuario.telefono %>
  </p>
</div>

app/views/mascotas/edit.html.erb
<h1>Editing mascota</h1>

<%= render "form", mascota: @mascota %>

<br>

<div>
  <%= link_to "Show this mascota", @mascota %> |
  <%= link_to "Back to mascotas", mascotas_path %>
</div>

app/views/mascotas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mascotas</h1>

<div id="mascotas">
  <% @mascotas.each do |mascota| %>
    <%= render mascota %>
    <p>
      <%= link_to "Show this mascota", mascota %>
    </p>
  <% end %>
</div>

<%# <%= raw pagy_nav(@pagy) %> %>

<%= link_to "New mascota", new_mascota_path %>

app/views/mascotas/new.html.erb
<h1>New mascota</h1>

<%= render "form", mascota: @mascota %>

<br>

<div>
  <%= link_to "Back to mascotas", mascotas_path %>
</div>

app/views/mascotas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mascota %>

<div>
  <%= link_to "Edit this mascota", edit_mascota_path(@mascota) %> |
  <%= link_to "Back to mascotas", mascotas_path %>

  <%= button_to "Destroy this mascota", @mascota, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Te Encontre</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 me-4">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if usuario_signed_in? %>
                Hola <%= current_usuario.nombre %>
            <% else %>
                Iniciar sesión
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <% if usuario_signed_in? %>
                <li><%= button_to 'Cerrar sesión', destroy_usuario_session_path, class: 'dropdown-item', method: :delete %></li>
            <% else %>
                <li><%= link_to 'Iniciar sesión', new_usuario_session_path, class: 'dropdown-item'%></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to 'Registro', new_usuario_registration_path, class: 'dropdown-item'%></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>